// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkARUkKvfHZmv0c-jlLRKQQzylBoNV1M',
    appId: '1:797970173318:web:404706fe4bba57c44ab007',
    messagingSenderId: '797970173318',
    projectId: 'aclub2',
    authDomain: 'aclub2.firebaseapp.com',
    storageBucket: 'aclub2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1QK_lCXF-HhOvokdfhKsvtGlPIGmmAes',
    appId: '1:797970173318:android:3a2188bb2731529d4ab007',
    messagingSenderId: '797970173318',
    projectId: 'aclub2',
    storageBucket: 'aclub2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjxiAxQHhegLkdF04I1aym-kGs9Eqvv9c',
    appId: '1:797970173318:ios:d63409ec36faa2c34ab007',
    messagingSenderId: '797970173318',
    projectId: 'aclub2',
    storageBucket: 'aclub2.firebasestorage.app',
    iosBundleId: 'com.aclub.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjxiAxQHhegLkdF04I1aym-kGs9Eqvv9c',
    appId: '1:797970173318:ios:d63409ec36faa2c34ab007',
    messagingSenderId: '797970173318',
    projectId: 'aclub2',
    storageBucket: 'aclub2.firebasestorage.app',
    iosBundleId: 'com.aclub.ui',
  );
}
